version: '3'

services:
    rbac-database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
          - '5433:5432'
        volumes:
          - ./var/postgres:/var/lib/postgresql/data

volumes:
    rbac-database: