version: '3'

services:
    rbac-database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
          - '5433:5432'
        volumes:
          - ./var/postgres:/var/lib/postgresql/data

    rabbitmq:
        image: rabbitmq:3.7.5-management
        working_dir: /app
        hostname: rabbit-mq
        container_name: 'rabbit-mq'
        ports:
          - 15672:15672
          - 5672:5672
        environment:
          RABBITMQ_DEFAULT_USER: user
          RABBITMQ_DEFAULT_PASS: password

volumes:
    rbac-database: